### ISSUE TITLE
Initialize model with pre-trained BART

### ISSUE THREAD

**Issue by chiyuzhang94** [Yuanhy1997/SeqDiffuSeq#12]
Hi @Yuanhy1997  ,

Thanks for your great work.

I wonder if you try to use the weights of pre-trained BART to initialize your model. I didn't find these results in the paper while I can see you have a knob to keep pre-trained weights in the code.

Best,
Chiyu

**Comment by Yuanhy1997** [comment]
Thx! We didn't initialize the weights with BART's pretrained weights. We initialize the model using the from_config function of transformers package, and the config would be slightly modified for our network architecture. That is a convenient way to initialize an encoder decoder architecture, and that's where we have to download the model config file for BART(not the weight file). I think initializing from pretrained weights is not really reasonable for a continuous diffusion model like ours. It would be really interesting to explore the pretraining in continuous diffusion text models.

**Comment by chiyuzhang94** [comment]
Got it! Make sense. 

Another question: did you use distributed training on multiple GPUs? Does the code support distributed training?
Thanks.

**Comment by Yuanhy1997** [comment]
Of course, you can refer to the script for WMT training.

**Comment by chiyuzhang94** [comment]
> 

I see. But I found it confusing. In the script, the number of GPU is 1: [NUM_GPUS=1](https://github.com/Yuanhy1997/SeqDiffuSeq/blob/ed56ca480002b89a26ebd16b0257e1aa880f80f1/train_scripts/iwslt_en_de.sh#L6)

**Comment by Yuanhy1997** [comment]
I just check the script and in the WMT training script I think the number is 8.

**Comment by chiyuzhang94** [comment]
Thanks for confirming. 
However, it doesn't work for me. 
Have you used "torch.distributed" API to run this code?

**Comment by Yuanhy1997** [comment]
If you meet some bugs, please add more information so that I can help. I don't know in what way "It doesn't work" for you. To run the code, we use mpi4py and launch with mpiexec.

**Comment by chiyuzhang94** [comment]
Sorry for the vague description. Let me clarify the issue I got.
I am running a job via the Slurm system. I added the following lines to the end of the script. 
```
export PARENT=`/bin/hostname -s`
export MPORT=$(( ((RANDOM<<15)|RANDOM) % 63001 + 2000 ))
export CHILDREN=`scontrol show hostnames $SLURM_JOB_NODELIST | grep -v $PARENT`
export HOSTLIST="$PARENT $CHILDREN"

export CUDA_VISIBLE_DEVICES=$HOSTLIST && mpiexec -n $NUM_GPUS -host $HOSTLIST python -u main.py "${ARGS[@]}"
```
The job got started but did not run into the model training. The log file shows this:
```
srun: error: Unable to create step for job 69942: Requested node configuration is not available
``` 

Any thoughts?

**Comment by Yuanhy1997** [comment]
From my experience of using slurm, it seems that the problem is not about the code. I think maybe you misuse the slurm and fail to create a job. If the job is created and you meet errors when running the code,  I think you can check the error log for more specific info.

**Comment by chiyuzhang94** [comment]
Ok. Thanks.

**Comment by chiyuzhang94** [comment]
For your reference, I solved the distributed training issue by replacing dist_util.py with the dist_util.py script from [DiffuSeq](https://github.com/Shark-NLP/DiffuSeq/blob/bdc8f0adbff22e88c8530d1f20c3c7589c061d40/diffuseq/utils/dist_util.py#L16). In my case, I cannot run a job with `mpiexec`. As result, `MPI.COMM_WORLD` cannot give me the correct environment variables and `dist.init_process_group` run out of waiting time.

**Comment by Yuanhy1997** [comment]
Somehow it's a good news that you successfully run the code. Still, I think the problem is about how you set environment on slurm (maybe just export some environment variable first), and as I can recall, MPI4PY is just another way of launching distributed model training and the code should work well on slurm.
