### ISSUE TITLE
About the paper results.

### ISSUE THREAD

**Issue by wutong4012** [Yuanhy1997/SeqDiffuSeq#15]
https://github.com/Yuanhy1997/SeqDiffuSeq/blob/ed56ca480002b89a26ebd16b0257e1aa880f80f1/bleu_eval.py#L19

I want to ask if the result 29.83 compared with the AR and CNAT is calculated by this code? And this result is test set or valid set?

Thanks~

**Comment by Yuanhy1997** [comment]
Yes, and we use the reported results from CNAT paper. The results are on the test set if not otherwise specified.
