### ISSUE TITLE
Data for wmt14 is missing

### ISSUE THREAD

**Issue by xipq** [Yuanhy1997/SeqDiffuSeq#16]
Hi, thanks for your great work. I would like to train your model on WMT14, but I haven't found your data used in the google drive link provided from this repo. Would you please double check it? Thanks.

**Comment by xipq** [comment]
Thanks for your reply, I will check the fairseq repo. BTW Looking forward to your release~

**Comment by Yuanhy1997** [comment]
Hi, I just uploaded the data, you can find it in README now.
