### ISSUE TITLE
关于训练时间的询问以及是否可以多卡训练的请教

### ISSUE THREAD

**Issue by Markkk111** [Yuanhy1997/SeqDiffuSeq#17]
您好，请问您使用v100训练100k大概花了多长时间啊？有没有多卡训练的版本使其能够在3090上快一点训练呢？恕我才疏学浅，还不能解决这个问题，如果您能提供回复，不胜感激！salute！
1、训练命令是：bash ./train_scripts/iwslt_en_de.sh 6 de en
2、显卡占用内存情况显示如下：
[0] NVIDIA GeForce RTX 3090 | 62°C, 100 % |  8085 / 24576 MB | seqdiffuseq(253M) seqdiffuseq(253M) seqdiffuseq(253M) seqdiffuseq(651M) xx (6357M) gdm(4M)
[6] NVIDIA GeForce RTX 3090 | 76°C,  99 % | 17810 / 24576 MB | seqdiffuseq(11141M) xx 6351M) gdm(4M)
3、大概两天的训练情况：
-----------------------
| grad_norm | 0.026    |
| loss      | 0.0315   |
| loss_q0   | 0.0172   |
| loss_q1   | 0.0266   |
| loss_q2   | 0.0354   |
| loss_q3   | 0.046    |
| mse       | 0.0304   |
| mse_q0    | 0.0161   |
| mse_q1    | 0.0254   |
| mse_q2    | 0.0341   |
| mse_q3    | 0.0448   |
| samples   | 2.53e+07 |
| step      | 1.98e+05 |
------------------------

**Comment by Yuanhy1997** [comment]
As I mentioned in README, it does not have to train 100k steps to get a good performance. For IWSLT it suffices to train around 30k steps. On A100, it is around 8 hours for 30k steps of training as far as I can recall. I would be a bit longer on 3090 I think.

**Comment by Markkk111** [comment]
Thank you for your reply, I apologize for my negligence and wish you all the best.
