### ISSUE TITLE
The self-conditioning part

### ISSUE THREAD

**Issue by CCCCCCCABC** [Yuanhy1997/SeqDiffuSeq#25]
I apply this adaptive technique by modifying my code, but the system prompts me
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by
87 making sure all `forward` function outputs participate in calculating loss.
88 If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable)

Can you give me a hint? About half using 0 and half using the Zt of the previous prediction？

Thanks!

**Comment by Yuanhy1997** [comment]
Sorry, the information you listed here is really limited. But when I encounter the same error like this, it usually indicates that some of the parameters in my DDP model are not included in the forward computation. If you are intended to exclude some params and making no errors, you can just set the find_unused_parameters arguments as suggested.

**Comment by CCCCCCCABC** [comment]
> Sorry, the information you listed here is really limited. But when I encounter the same error like this, it usually indicates that some of the parameters in my DDP model are not included in the forward computation. If you are intended to exclude some params and making no errors, you can just set the find_unused_parameters arguments as suggested.

Yes, about the 50% chance that you used the last Zt and passed forward(), but did not backpropagate, this will cause an error in DDP. Because the last Zt did not participate in the update. When I set find_unused_parameters=True, I still get an error. Did you use self.ddp_model = True or self.ddp_model = False?

Thanks !

**Comment by Yuanhy1997** [comment]
Sorry I cannot recall exactly, but I think I have used DDP to enable data parallel distributed training. The last Zt should be pure Gaussian noise as far as I can remember?

**Comment by CCCCCCCABC** [comment]
> Sorry I cannot recall exactly, but I think I have used DDP to enable data parallel distributed training. The last Zt should be pure Gaussian noise as far as I can remember?

Yes, it's been a long time, but thank you for your work. 

With best wishes！
