### ISSUE TITLE
the meaning of loss name in the output

### ISSUE THREAD

**Issue by BaohaoLiao** [Yuanhy1997/SeqDiffuSeq#5]
Hi,

when I run your code, I get the output like: 
```
| loss      | 0.0201   |
| loss_q0   | 0.0202   |
| loss_q1   | 0.0201   |
| loss_q2   | 0.0202   |
| loss_q3   | 0.0199   |
| mse       | 0.0201   |
| mse_q0    | 0.0202   |
| mse_q1    | 0.0201   |
| mse_q2    | 0.0202   |
| mse_q3    | 0.0199   |
```
what is the difference between loss and loss_qi for i in [0,3].

**Comment by Yuanhy1997** [comment]
The numbers after q are the quantiles for the diffusion timesteps, and those without q* are the overall averaged losses.

**Comment by BaohaoLiao** [comment]
Thank you for your quick response. So the larger the number after q, the closer to T?

**Comment by Yuanhy1997** [comment]
I think so, while you can double check the code. I cannot remember exactly.

**Comment by BaohaoLiao** [comment]
Sure, thank you very much

**Comment by BaohaoLiao** [comment]
Here I want to check whether I understand your code correctly.
